version: "3.4"
services:
  elasticsearch:
    image: elasticsearch:7.9.2
    environment:
       - discovery.type=single-node
       - bootstrap.memory_lock=true
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
       - "ELASTIC_PASSWORD=elasticsearch"
    ulimits:
       memlock:
         soft: -1
         hard: -1
    volumes:
       - elasticsearch-volume:/usr/share/elasticsearch/data
    ports:
       - 9200:9200
       - 9300:9300
    networks:
       - postgre_default
  logstash:
    image: logstash:7.9.2   
    ports:
      - "5000:5000"
    volumes:
      - ../conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ../conf/postgresql-42.5.0.jar:/usr/share/logstash/postgresql-42.5.0.jar
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf --verbose
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx256m"
    depends_on:
      - elasticsearch
    networks:
      - postgre_default
  kibana:
    image: kibana:7.9.2
    volumes:
      - kibana-volume:/usr/share/kibana/
    ports:
     - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - postgre_default


networks:
  postgre_default:
    external:
      name: postgre_default
volumes:
  kibana-volume:
    external: true
  elasticsearch-volume:
    external: true