version: '3.3'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=87654321
  pgadmin:
    image: dpage/pgadmin4
    ports:
     - "5433:80" 
    environment:
     - PGADMIN_DEFAULT_EMAIL=developer@example.com
     - PGADMIN_DEFAULT_PASSWORD=12345678
    depends_on:
     - postgres 
volumes:
  postgres-data: 